### ISSUE TITLE
How to use this gem in rails application with sustainability

### ISSUE THREAD

**Issue by abigoroth** [NullVoxPopuli/action_cable_client#26]
Hi, 
I have a rails app and another rails app with actioncable channel. I need to communicate between these two rails app using actioncable. Is there an example using this gem. And how to ensure the socket will reconnect if let say disconnected for many hours.

thanks in advance!

**Comment by NullVoxPopuli** [comment]
hello, @abigoroth 
I don't know of an example, but if you come up with one, I'll be sure to link to it in the readme :-)

But as for ensuring a connection, the only way to do this is to hook in to the ping/pong messages, and if you don't receive a ping or pong (depending on which end of the socket you're on), you can assume a disconnection and start the re-connect process.
It also may be worth pushing all your messages into a queue so that when there is a disconnect, you can ensure that all messages get sent.

Hope this helps!

**Comment by hansololai** [comment]
Hi, I have just setup one using a modified version of action cable.  Basically I extended this class and setup reconnection method. I can upload some code if you need example. Since it's 10 days ago, I am not sure if you still have this problem.

**Comment by NullVoxPopuli** [comment]
@hansololai, would you want to open a PR to implement reconnect?

**Comment by NullVoxPopuli** [comment]
A comment on reconnect behavior over here: https://github.com/NullVoxPopuli/action_cable_client/issues/25#issuecomment-378057801
